### ISSUE TITLE
starRoll - 10% chance logic not functioning as intended

### ISSUE THREAD

**Issue by derycka** [PacktPublishing/Swift-Game-Development-Third-Edition#4]
Intended logic: Each encounter has a 10% chance to spawn a star

Short answer: The starRoll chance logic should be contained inside code that checks to see if we should set a new encounter for this to function.   The code relating to spawning a star, or heart crate is then ONLY run if we set a new encounter.

Currently, EVERY time didSimulatephysics() fires this code is run.

Issue fixed in my accompanying Pull Request.

**Comment by sarvesh-packt** [comment]
Hi,

Please reopen if the issue still persists.

Thanks,
