### ISSUE TITLE
HUD displays over character (Penguin) BEFORE falling to the ground

### ISSUE THREAD

**Issue by derycka** [PacktPublishing/Swift-Game-Development-Third-Edition#5]
Intended functionality: When die() runs, allow the Penguin to fall to the ground (gravity) BEFORE displaying the HUD.

Existing functionality:
The HUD appears prematurely at gameOver(), causing the die() animation of the Penguin to not be viewable in the foreground.

Fixed in my accompanying Pull Request.

**Comment by sarvesh-packt** [comment]
Hi,

Please reopen if the issue still persists.

Thanks,
