### ISSUE TITLE
UI: sliderKnob location wrong when the volume set to 0

### ISSUE THREAD

**Issue by derycka** [PacktPublishing/Swift-Game-Development-Third-Edition#6]
This update fixes a visual issue that occurs to the sliderKnob location if the volume is set to 0.

If the volume is set at 0, it follows that the exisiting math will equal 0:
let pos = (Float)(sliderBase.position.x + sliderBase.frame.size.width) * volume

Hence, with the existing sliderBase.position = CGPoint(x: 50, y: 0) the sliderKnob will appear in the wrong place upon re-entering the Options Scene. (visual UI bug)
The easy fix.. set sliderBase.position = CGPoint(x: 0, y: 0)

My accompanying Pull Request fixes the issue.

**Comment by sarvesh-packt** [comment]
Hi,

Please reopen if the issue still persists.

Thanks,

**Comment by sarvesh-packt** [comment]
Hi,

Please reopen if the issue still persists.

Thanks,
