### ISSUE TITLE
Chapter 4 to 10b  Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Cashubski** [PacktPublishing/Swift-Game-Development-Third-Edition#7]
if self.physicsBody!.velocity.dy > 300 { This line gives the error above. I don't know how to fix it however, people are saying that self.physicsBody is nill

**Comment by sidshekar** [comment]
Run the code in BigSur/ Xcode 12 beta, as It seems it is a bug in Xcode 11.x or Catalina, which is causing this error. See screenshot below. 

![image](https://user-images.githubusercontent.com/2862097/86961897-1ba18400-c1b6-11ea-8b11-440f4d01d6de.png)


**So i would advise to create a partition on mac and install Bigsur beta/ Xcode 12 beta and run it there as it runs fine there.**

![image](https://user-images.githubusercontent.com/2862097/86961916-252aec00-c1b6-11ea-99ea-43c7e9a633d6.png)
